# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: recom_repo
          POSTGRES_PASSWORD: password
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Hex
          command: mix local.hex --force
          working_directory: backend/recom
      - run:
          name: Install Rebar
          command: mix local.rebar --force
          working_directory: backend/recom
      - restore_cache:
          name: restore dependencies from cache
          key: recom-cache-{{ checksum "mix.lock" }}
      - run:
          name: Fetch mix dependencies
          command: mix deps.get
          working_directory: backend/recom
      - run:
          name: Compile dependencies
          command: mix deps.compile
          working_directory: backend/recom
      - run:
          name: Compile the project
          command: mix compile
          working_directory: backend/recom
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Add docker host entry to enable ecto to connect to postgres
          command: echo 127.0.0.1 docker | sudo tee -a /etc/hosts
      - run:
          name: Create the database
          command: mix ecto.create
          working_directory: backend/recom
      - run:
          name: Migrate the database
          command: mix ecto.migrate
          working_directory: backend/recom
      - run:
          name: Run the tests
          command: mix test
          working_directory: backend/recom
      - save_cache:
          name: Cache dependencies
          key: recom-cache-{{ checksum "mix.lock" }}
          paths:
            - backend/recom/deps
            - backend/recom/_build
